# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install -g @angular/cli
    npm install
    ng build web-portal
  displayName: 'npm install and build'

- task: CopyFiles@2
  inputs:
    Contents: 'dist/web-portal/**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'

- task: NuGetCommand@2
  inputs:
    command: 'pack'
    packagesToPack: 'Microsoft.HPC.WebPortal.nuspec'
    versioningScheme: 'byBuildNumber'