# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

name: 1.0.$(Rev:r)

trigger:
  batch: true
  branches:
    include:
    - master
    - release
  paths:
    exclude:
    - README.md
    - CONTRIBUTING.md
    - LICENSE

pr:
  branches:
    include:
    - master
  paths:
    exclude:
    - README.md
    - CONTRIBUTING.md
    - LICENSE

stages:
- stage: Build
  jobs:
  - job: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - checkout: self
      submodules: recursive

    - task: NodeTool@0
      inputs:
        versionSpec: '10.x'
      displayName: 'Install Node.js'

    - script: |
        npm ci
      displayName: 'Install npm Packages'

    - script: |
        echo "CHROMEWEBDRIVER: $CHROMEWEBDRIVER"
        npm run ng e2e --protractor-config=e2e/protractor-ci.conf.js --port 4400 --chromeDriver="$CHROMEWEBDRIVER"
      displayName: 'E2E Test'

    - script: |
        npm run build-prd
      condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/release'))
      displayName: 'Build'

    - script: |
        ./make-zip $BUILD_BUILDNUMBER
      condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/release'))
      displayName: 'Package Build Result'

    - publish: 'dist/WebPortal-$(Build.BuildNumber).zip'
      artifact: Package
      condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/release'))
      displayName: 'Publish Build Result'
