# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

name: 1.1.$(Rev:r)

trigger:
  batch: true
  branches:
    include:
    - master
  paths:
    exclude:
    - README.md
    - CONTRIBUTING.md
    - LICENSE

pr:
  branches:
    include:
    - master
  paths:
    exclude:
    - README.md
    - CONTRIBUTING.md
    - LICENSE

stages:
- stage: Build
  jobs:
  - job: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - checkout: self
      submodules: recursive

    - task: NodeTool@0
      inputs:
        versionSpec: '10.x'
      displayName: 'Install Node.js'

    - script: |
        npm ci
      displayName: 'Install npm Packages'

    - script: |
        npm run ci-test
      displayName: 'Unit Test'

    - task: PublishTestResults@2
      inputs:
        testResultsFiles: 'unit-test-result.xml'
        failTaskOnFailedTests: true
      displayName: 'Publish Unit Test Result'

    - task: PublishCodeCoverageResults@1
      inputs:
        codeCoverageTool: cobertura
        summaryFileLocation: coverage/cobertura-coverage.xml
      displayName: 'Publish Unit Test Code Coverage Result'

    # E2E test may fail in Azure Pipeline as the version of Chrome installed on the pool image
    # doesn't always match the version of ChromeDriver specified in package-lock.json. So
    # skip E2E for now.
    #
    # - script: |
    #     npm run ci-e2e
    #   displayName: 'E2E Test'

    - script: |
        npm run build-prd
      condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
      displayName: 'Build'

    - script: |
        ./make-zip $BUILD_BUILDNUMBER
      condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
      displayName: 'Package Build Result'

    - publish: 'dist/WebPortal-$(Build.BuildNumber).zip'
      artifact: Package
      condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
      displayName: 'Publish Build Result'
