# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

name: 0.0.$(Rev:r)

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: self
  submodules: recursive

- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install -g @angular/cli
    npm install
  displayName: 'Install Angular Cli and npm packages'

- script: |
    ng build -c staging
  displayName: 'Ng Build'

- task: CopyFiles@2
  inputs:
    Contents: 'dist/web-portal/**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
  displayName: 'Copy build result'

- task: NuGetCommand@2
  inputs:
    command: 'pack'
    packagesToPack: 'Microsoft.HPC.WebPortal.nuspec'
    versioningScheme: 'byBuildNumber'
    packDestination: '$(Build.ArtifactStagingDirectory)'
  displayName: 'Make NuGet package'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
  displayName: 'Publish build result to Artifacts'

- task: NuGetCommand@2
  inputs:
    command: 'push'
    packagesToPush: $(Build.ArtifactStagingDirectory)/**/Microsoft.HPC.WebPortal.*.nupkg
    nuGetFeedType: 'internal'
    publishVstsFeed: '5e2011c9-a9d1-448b-9be7-9e9c97526134'
  displayName: 'Publish NuGet package to internal feed'
